added chromedriver update to cucumber command
makandra/geordi pull request #116
Opened 2020-09-11 11:15 UTC by brunosedler

The duration of the update_chromedriver command (if installation is skipped) is between 133 and 140ms (measured with `time`  bash command). Without checking for version equality it was about 116 to 118 ms, so the equality check takes about 20ms

2020-09-14 06:52 UTC, codener requested changes

2020-09-14 06:52 UTC, codener commented on lib/geordi/commands/cucumber.rb
> +    invoke_geordi 'chromedriver_update', show_warning: false
Ok, we won't add a test because it is just too hard to fake the Chrome/chromedriver version determination.

2020-09-14 06:52 UTC, codener commented on lib/geordi/chromedriver_updater.rb
> +        Interaction.warn("No update required, you are using for both executables the same version #{chrome_version}!") if options.show_warning
Please turn this into an `Interaction.note`, as it is nothing to worry about.

2020-09-14 06:52 UTC, codener commented on lib/geordi/commands/chromedriver_update.rb
> +  desc: 'Show a warning if the chrome and chromedriver versions are already the same and nothing needs to be done.'
I have objections regarding the option naming. "show warning" could be about anything. Let's get a bit closer to the actual thing we want here. What about `quiet_if_matching`? Default would be false, and the "no update" note would not be printed if the option is true.

Please also shorten the option description to about half its current length. This keeps it from wrapping when printed on the bash (confer `geordi help cucumber` > debug option description).

2020-09-14 15:41 UTC, codener requested changes
Thanks for the polishing! Please drop the question mark in the new option, then merge to master.

We'll not release it instantly, but instead use it locally for a while to see how it behaves.

2020-09-16 11:59 UTC, codener approved these changes
Fine, merge it!

2020-09-18 09:17 UTC, codener commented
@brunosedler I just found an important case we missed: Some users of Geordi may not be using chromedriver at all. Running `chromedriver-update` would break the Cucumber command for them. I see two possible solutions:

* Add a config option `autoupdate-chromedriver` for `.geordi.yml` and document it. The auto-updating should only take place when the option is set.
* Check whether `chromedriver` is present in the system, and run the update check if it is.

What do you think?

2020-09-23 09:03 UTC, brunosedler commented
@codener I think I like the first option better. The second one would add some more time to running the features, although we might have to check how long it takes. But if you don't have chromedriver it is annoying that it takes longer due to something you don't even need. So I like the "opt in" option better. Especially because we already thought about showing a message and ask permission to run the update, so with option one it would be something a user agrees to.

2020-09-23 09:33 UTC, codener commented
Checking for a `chromedriver` executable takes around 3ms – that's almost instant. Still a secret update might not be desirable for all users. Lets go with the config option.

- The option should be called "autoupdate-chromedriver". Please choose the casing (spinal/camel/snake) so that it does not need to be quoted in the yml file.
- Please document the option in the `long_desc` of the `chromedriver-update` command.
- Rebase on `master`
- Please add an entry to the CHANGELOG describing the new feature

2020-09-24 05:18 UTC, codener approved these changes
Super Sach!

2020-09-28 08:13 UTC, closed without merging